### ISSUE TITLE
make it possible to set the libdir to /usr/lib64

### ISSUE THREAD

**Issue by jenningsloy318** [ukui/peony-extensions#24]
On fedora, the default libdir is /usr/lib64, not /usr/lib, should make it possible to  determine the correct path by compiler, not hard coded in source code

**Comment by Yue-Lan** [comment]
the idea is good... but there might be some difficult.

as you said, peony load /usr/lib/peony-extensions in source code. That means we have to handle the problem not only here, but also in peony.

It is not nesasersary to put peony extensions into system libdir, because it just a 'protocol' for plugin loading. If it not affect using, I perfer to let the problem be left.

**Comment by jenningsloy318** [comment]
but if you leave there, when packaging it on fedora/rpm, we have manually edit it everytime

**Comment by Yue-Lan** [comment]
c1171de96f61e834b932806a5c5b0d50eef1aa27 解决了这个问题
